collections:
  - name: community.crypto
  - name: community.general
  - name: community.proxmox
  - name: devsec.hardening
  - name: debops.debops
  #- name: linux-system-roles.storage
  - name: mila.proxmox
