all:
  hosts:
    mediaserver:
      ansible_host: 192.168.1.208
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/media-server_ed25519
      ansible_ssh_common_args: '-o IdentitiesOnly=yes'

  children:
    servers:
      hosts:
        mediaserver:
