all:
  children:
    lab:
      hosts:
        mediaserver:
          ansible_host: 192.168.1.208
        workstation1:
          ansible_host: 10.3.0.3
        tnas:
          ansible_host: 10.3.0.4

    node:
      children:
        debian:
          hosts:
            tnas:

    servers:
      hosts:
        mediaserver:

    workstations:
      hosts:
        workstation1:
