all:
  children:

    # =========================
    # Proxmox nodes (reálne stroje)
    # =========================
    pve_nodes:
      hosts:
        pve:

    # =========================
    # Proxmox VM definície (NEPRIPÁJAŤ SA SSH)
    # - slúžia len ako "objects" pre qm/API
    # =========================
    pve_vms:
      children:

        # ---- Templates
        pve_templates:
          children:
            haos_templates:
              hosts:
                tpl_haos_17:
            debian_templates:
              hosts:
                tpl_debian_12:

        # ---- Instances (VM ktoré budeš vytvárať/klonovať)
        pve_instances:
          children:
            haos_instances:
              hosts:
                vm_haos_duko:
            debian_instances:
              hosts:
                vm_testgoldimage:

    # =========================
    # SSH-managed hosts (reálne OS, kam sa Ansible pripája)
    # Sem patria: VPS, servery, workstations, a VM až keď majú IP+SSH
    # =========================
    managed:
      children:

        pve:
          hosts:
            pve:

        vps:
          hosts:
            vps_hetz_1:

        servers:
          hosts:
            mediaserver:
            tnas:

        workstations:
          hosts:
            workstation1:
            htpc1:

        # VM po deployi (keď už majú sieť a SSH)
        # Nezamieňaj s pve_vms definíciami.
        vms_ssh:
          children:
            haos_vms_ssh:
              hosts:
                homeassistant_duko:
            debian_vms_ssh:
              hosts:
                testgoldimage:

    # =========================
    # WireGuard skupiny (cieľové stroje s reálnou konektivitou)
    # =========================
    wg_servers:
      hosts:
        vps_hetz_1:

    wg2_media_peers:
      hosts:
        mediaserver:
        tnas:
        workstation1:

    wg3_mgmt_peers:
      hosts:
        workstation1:
        tnas:
        mediaserver:
