all:

  hosts:
    vps-hetz-1:
      ansible_host: 46.225.23.194

    mediaserver:
      ansible_host: 192.168.1.208

    workstation1:
      ansible_host: 10.3.0.3

    tnas:
      ansible_host: 10.3.0.4

    pve1:
      ansible_host: pve1
      ansible_port: 22
      ansible_user: ansible

    htpc1:
      ansible_host: 10.3.0.6

    testgoldimage:

  children:

    wg-servers:
      hosts:
        vps-hetz-1:
          ansible_host: 49.12.200.47

    wg2_media_peers:
      hosts:
        mediaserver:
          wg_ip: 10.2.0.2
          wg2_routed_subnets: ["172.30.0.0/24"]
        minipc-travelnas:
          wg_ip: 10.2.0.5
        laptop-joseph:
          wg_ip: 10.2.0.6

    wg3_mgmt_peers:
      hosts:
        ansible-controller:
          wg_ip: 10.3.0.2
        tnas:
          wg_ip: 10.3.0.4
        media-stack-v2:
          wg_ip: 10.3.0.212

    bootstrap:
      hosts:
        vps-hetz-1:

    managed:
      hosts:
        vps-hetz-1:

    vps:
      hosts:

    vpn:
      hosts:

    lab:
      hosts:
        mediaserver:
        workstation1:
        tnas:
        pve1:

    servers:
      hosts:
        mediaserver:
        media_stack_v2:
          ansible_host: 10.3.0.212

    workstations:
      hosts:
        workstation1:

    pve:
      children:
        pve_vms:
          hosts:
            testgoldimage:
              